#!/usr/bin/env ruby
require 'yaml'

settings = YAML::load(File.open(File.expand_path("~/.fsmon")))

@user = settings['user']
@psw  = settings['psw']

path = File.dirname(__FILE__)

Dir.chdir path

%x{echo #{@pwd} | sudo -S ./fsmond.rb start} if @psw
%x{sudo ./fsmond.rb start} if not @psw
%x{./fsfetchd.rb start}
